# Generated by Django 6.1 on 2026-08-23 16:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0002_medicinebatch'),
        ('prescriptions', '0002_prescriptionitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('dispensed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicine_dispensings', to=settings.AUTH_USER_MODEL)),
                ('medicine_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensings', to='medicines.medicinebatch')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensings', to='prescriptions.prescriptionitem')),
            ],
            options={
                'ordering': ['-dispensed_at'],
            },
        ),
    ]
